### ISSUE TITLE
[Feature Request] Custom User-Agent

### ISSUE THREAD

**Issue by chromer030** [agourlay/dlm#10]
In some situations without custom user-agent , downloading is not possible, and server doesn't respond to request because only specific or very recent or standard browser's UA are accepted, for example streaming websites.
Please consider implementing this essential feature.

Proposed feature look likes this :
```
dlm -U 'user agent'
dlm -U 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36' 
```

**Comment by agourlay** [comment]
This sounds reasonable and should be pretty easy to implement :+1:

**Comment by agourlay** [comment]
Fixed in https://github.com/agourlay/dlm/commit/3485a7f87604670395b92f7d0a4768d5242a7a0d.
Will be part of the next release.

**Comment by chromer030** [comment]
vielen dank !

**Comment by agourlay** [comment]
@chromer030 [0.2.3](https://github.com/agourlay/dlm/releases/tag/v0.2.3) is out :rocket: 
Please give those two new features a try!

**Comment by chromer030** [comment]
Tested and working like charm, thanks alot.
```
./dlm -i 1.txt -M 1 -o . --proxy http://127.0.0.1:10809 -U 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36'
[2022-01-31 23:56:17] Starting dlm with at most 1 concurrent downloads
[2022-01-31 23:56:17] Found 1 URLs in input file 1.txt
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 0/1
google-chrome-stable_current_amd64. [00:00:26] [###>------------------------------------] 7.69MiB/86.65MiB (speed:998.92KiB/s) (eta:2m)
```
