### ISSUE TITLE
[Feature Request] Auto Retry

### ISSUE THREAD

**Issue by chromer030** [agourlay/dlm#11]
The tool really needs a feature to automatically retry the failed download based on the specified time.

Proposed feature look likes this :
```
dlm -R retry time
dlm -R 10 'URL /--inputFile'
```

**Comment by agourlay** [comment]
There is already a retry strategy implemented in `dlm`.
https://github.com/agourlay/dlm/blob/22350c9c920ff47db8603046256512bf8e5d4cc1/src/main.rs#L99-L101

This is an exponential backoff with at most 10 retries.

Is this covering your needs?

**Comment by chromer030** [comment]
Thank you very much , can we have an option for more than 10 ?
for example dlm -r 20 ?

**Comment by agourlay** [comment]
Fixed in [d320648](https://github.com/agourlay/dlm/commit/d5bb080bed4924495bb2b712540ef6ecc4da6ac3)
Will be part of the next release.
