### ISSUE TITLE
[Feature Request] Native in-app Proxy Support

### ISSUE THREAD

**Issue by chromer030** [agourlay/dlm#14]
You kindly proposed an workaround for using the tool behind the proxy , https://github.com/agourlay/dlm/issues/6#issuecomment-1022990809 , It's working , thank you.
But i think, in-app option for supporting proxies like Socks,HTTPS,HTTPS is more stable, most of download managers have this feature natively.
Thank you for developing this useful tool , i hope one day it will be the most used download-manager , as the tools like aria2 are unmaintained and there is active needs for a good alternative.

**Comment by agourlay** [comment]
This sounds reasonable and should be pretty easy to implement :+1:

**Comment by agourlay** [comment]
Fixed in https://github.com/agourlay/dlm/commit/d3206489fc99d4e8115cf0927cc8f600a28883ed
Will be part of the next release.
