### ISSUE TITLE
[Bug] Speed miscalculation on download resume

### ISSUE THREAD

**Issue by chromer030** [agourlay/dlm#19]
```
user@user ~/Desktop % ./dlm -i dlm.txt -M 1 -o /run/media/user/Data/
[2022-02-04 18:26:48] Starting dlm with at most 1 concurrent downloads
[2022-02-04 18:26:48] Found 1 URLs in input file dlm.txt
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 0/1
InstallAssistant.pkg        [00:00:11] [##################################>-----] 9.87GiB/11.32GiB (speed:953.67MiB/s) (eta:2s)
```

**Comment by chromer030** [comment]
And sometimes speed and eta are 0 forever !

![Screenshot_20220210_162826](https://user-images.githubusercontent.com/13361552/153404732-d944b061-8359-4e40-8756-5364f6a02cf1.jpg)

**Comment by agourlay** [comment]
[0.2.6](https://github.com/agourlay/dlm/releases/tag/v0.2.6) was released with the update to the latest RC from indicatif.

You could give it a try to see if it fixes this issue.

**Comment by agourlay** [comment]
Closing as I have not witnessed this issue in the latest versions.
