### ISSUE TITLE
Use it as a library

### ISSUE THREAD

**Issue by basicfunc** [agourlay/dlm#191]
Hey, there! I want to use this project in my project, can you please provide it as library?

**Comment by agourlay** [comment]
That's not really on my roadmap to be honest.

Have you seen the [trauma](https://crates.io/crates/trauma) library? I think it should do the job.

**Comment by basicfunc** [comment]
> That's not really on my roadmap to be honest.
> 
> Have you seen the [trauma](https://crates.io/crates/trauma) library? I think it should do the job.

Thanks for pointing this out, yeah it will work for me.
