### ISSUE TITLE
[Feature Requests]

### ISSUE THREAD

**Issue by chromer030** [agourlay/dlm#8]
If possible please implement this features to make this tool more feature-rich.
1- Direct receiving URL from command-line `dlm URL`
2- Custom User-agent `dlm -U 'USER-AGENT'`
3- Retry option when facing error `dlm -r 10`
4- Multi-Threaded and Multi-Connection downloading `dlm -s 16`
5- ARM binaries for macOS, Linux, Windows.

Vielen dank.

**Comment by agourlay** [comment]
Hi @chromer030 :wave: 

Thank you for your interest in `dlm`! 
Could you please create one Github issue per feature with an appropriate description.

This would help us track work and give us more fine grained spaces for discussions.

**Comment by chromer030** [comment]
Sure ! , thank you very much for attention and efforts of this useful tool.
