### ISSUE TITLE
[Feature Request] Receive and process URL directly from user and command-line instead of file.

### ISSUE THREAD

**Issue by chromer030** [agourlay/dlm#9]
Currently `dlm` feeds the URLs from external file via `--inputFile` switch , this is a great and useful option because brings us queue downloading. Thanks for it.

But sometimes we have just 1 URL for download and creating a file.txt and pasting URL and then feeding it in `dlm` is too much work.
I think lack of feature of direct processing URL is felt. 

Proposed feature look likes this :
```
dlm "URL"
dlm "https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb"
```

**Comment by agourlay** [comment]
I am not sure about this feature TBH.
There are already so many tools for single file download.

Why would `dlm` be a good fit for this use case?

**Comment by chromer030** [comment]
DLM is already really good tool , thank you very much for all efforts, but i think with this feature it will become more feature-rich and all-in-one tool.
It can be a feature alongside other features.
But decision is yours , i respect whatever you decide, this tool is already very good.

**Comment by agourlay** [comment]
I decided that the cost of this feature is not worth the value provided given that other tools, such as `wget`, are made for this use case.

Closing the issue for the time being until I change my mind :thinking:
